name: python-ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pip
  - pip:
    - PyX>=0.14.1
# Usage:
#   conda env create -f environment.yml
#   conda activate python-ds
