name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - seaborn
  - pip
  - pip:
    - folium
# Usage:
#   conda env create -f environment.yml
#   conda activate ml
